# Laradose
# Author: Adrien Poupa
# https://github.com/AdrienPoupa/laradose

version: '3.7'

services:
  mysql:
    image: "mysql:${MYSQL_VERSION}"
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel

  x-php:
    &php-base
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
      dockerfile: ./docker/php/Dockerfile
    environment:
      PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./:/var/www
    working_dir: /var/www
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - laravel

  php:
    <<: *php-base
    environment:
      PHP_VERSION: ${PHP_VERSION}
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${NGINX_HTTPS_PORT}:443"
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/keys:/etc/nginx/ssl
    networks:
      - laravel

  artisan:
    <<: *php-base
    depends_on:
      - mysql
    entrypoint: ['php', '/var/www/artisan']

  composer:
    image: composer:latest
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: "composer --ignore-platform-reqs"
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - laravel

  npm:
    image: node:12
    ports:
      - "${BROWSERSYNC_PORT}:3000"
      - "${BROWSERSYNC_ADMIN_PORT}:3001"
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    environment:
      MIX_MODE: ${MIX_MODE}
      MIX_BROWSERSYNC: ${MIX_BROWSERSYNC}
    command: sh -c "npm install && npm run ${MIX_MODE}"
    volumes:
      - ./:/var/www
      - ./docker/nginx/keys:/etc/ssl
    working_dir: /var/www
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - laravel

networks:
  laravel:
