version: '3.7'

services:
  # Redis should be installed when using Laravel Horizon
  horizon:
    environment:
      PHP_VERSION: ${PHP_VERSION}
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - composer
    working_dir: /var/www
    entrypoint: ['/var/www/artisan', 'horizon']
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - laravel
